#decorations = "none"

[colors.bright]
black = "#4C566A"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#81a1c1"
red = "#BF616A"
white = "#88c0d0"
yellow = "#EBCB8B"

[colors.normal]
black = "#3B4252"
blue = "#81A1C1"
cyan = "#88C0D0"
green = "#4C566A"
magenta = "#81a1c1"
red = "#BF616A"
white = "#88c0d0"
yellow = "#EBCB8B"

[colors.primary]
background = "#2e3440"
foreground = "#88c0d0"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "Lekton Nerd Font"


[font.offset]
x = 1
y = 1

[scrolling]
history = 5000

[window]
opacity = 1
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
